---
##################################################
# Define tasks
##################################################

- block:
  - name: Install repository of MongoDB
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
      mode: '0644'
  when: ansible_os_family == "RedHat"

- block:
  - name: Install a gnupg
    package:
      name: gnupg
      state: present
  - name: Add key for MongoDB
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-5.0.asc
      state: present
  - name: Register MongoDB repository
    shell: |
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  when: ansible_os_family == "Debian"

- name: Install MongoDB
  package:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Start mongodb and Enable autostart
  systemd:
    name: mongod
    state: started
    enabled: yes