---
##################################################
# Define tasks
##################################################

- block:
  - name: Install repository of MongoDB
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
      mode: '0644'
  when: ansible_os_family == "RedHat"

- block:
  - name: Add key for MongoDB
    command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
  - name: Register MongoDB repository
    shell: |
      echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list
  when: ansible_os_family == "Debian"

- name: Install MongoDB
  package:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Start mongodb and Enable autostart
  systemd:
    name: mongod
    state: started
    enabled: yes