---
##################################################
# Define executable roles
##################################################

- name:   Install common packages
  hosts:  all
  connection: local
  become: yes
  roles:
    - name: common/locale
      tags: locale
    - name: common/packages
      tags: packages
    - name: common/users
      tags: users
    - name: common/times
      tags: times

  post_tasks:
    - name: Restart machine
      shell: |
        sleep 2
        shutdown -r now "Ansible initialized"
      async: 5
      poll: 0
      # ignore_errors: true

    - name: Wating for server to come back
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        state: started
        delay: 30
        timeout: 300
      delegate_to: localhost
