---
##################################################
# Define executable roles
##################################################

- name:   Install packages
  hosts:  all
  connection: local
  become: yes
  roles:
    - name: apache
      tags: apache
    - name: docker
      tags: docker
    - name: go
      tags: go
    - name: jenkins
      tags: jenkins
    - name: laravel
      tags: laravel
    - name: mailhog
      tags: mailhog
    - name: mariadb
      tags: mariadb
    - name: memcached
      tags: memcached
    - name: minio
      tags: minio
    - name: mongodb
      tags: mongodb
    - name: mysql
      tags: mysql
    - name: nginx
      tags: nginx
    - name: php
      tags: php
    - name: redis
      tags: redis
    - name: ruby
      tags: ruby
    - name: yarn
      tags: yarn
