---
##################################################
# Define executable roles
##################################################

- name:   Install packages
  hosts:  all
  connection: local
  become: yes
  roles:
    - name: apache
      tags: apache
    - name: docker
      tags: docker
    - name: go
      tags: go
    - name: jenkins
      tags: jenkins
    - laravel
    - name: mailhog
      tags: mailhog
    - name: mariadb
      tags: mariadb
    - memcached
    - name: minio
      tags: minio
    - mongodb
    - nginx
    - php
    - name: redis
      tags: redis
    - ruby
    - yarn
#    - deploy
