---
##################################################
# Define tasks
##################################################

- name: Download go.
  get_url:
    url: "https://dl.google.com/go/go{{ go_os }}-{{ go_arch }}.tar.gz"
    dest: /usr/local/src
    checksum: "{{ go_checksum }}"

- name: Unarchive a file.
  unarchive:
    src: /usr/local/src/go{{ go_os }}-{{ go_arch }}.tar.gz
    dest: /usr/local

- name: Create symlinks.
  file:
    src: /usr/local/go/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - "go"
    # - "godoc"
    - "gofmt"
